to_feature_store: False
random_state: 2024
debug_output: {
  "ingest_sales": True,
  "ingest_markets": False,
  "ingest_german_gdp": False,
  "preprocess_sales": True,
  "preprocess_markets": False,
  "market_merge_german_gdp": False,
  "market_features_selection": False,
}

validation_fraction: 0.8
date_column: 'full_date'
target_column: 'sales_eur'
target_product: '#1'
num_feature_cols: 0

fit_params_Prophet: { 
    }

fit_params_NeuralProphet: {
        'freq': 'M',
        'batch_size': 4,
        'metrics': 'RMSE',
        'progress': 'print',
        'epochs': 20
    }
