to_feature_store: False
random_state: 2024

validation_fraction: 0.8
date_column: 'full_date'
target_column: 'sales_eur'
target_product: '#1'

num_feature_cols: 0

# for model training
fit_params_Prophet: { 
    }

fit_params_NeuralProphet: {
        'freq': 'M',
        'batch_size': 4,
        'metrics': 'RMSE',
        'progress': 'print',
        'epochs': 20
    }

# For drift detection
historical_feature_name: "sales_eur"
prepared_feature_name: "y"
p_val_drift_threshold: 0.05